# Generated by Django 4.1.7 on 2024-04-21 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edit',
            name='text',
        ),
    ]
