# Generated by Django 4.1.7 on 2024-04-22 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0002_remove_edit_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Edit',
        ),
        migrations.DeleteModel(
            name='Wiki',
        ),
    ]
